[postgres]
url = "postgresql://postgres.bnfpeakatnffesobziml:tejaK1101%21%21%21@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres"

[users]
Teja = "12345"
Carl = "12345"

[notifications]
webhook_url = "https://hooks.zapier.com/hooks/catch/28205183/4uklm2f/"
